"""initial_schema

Revision ID: d325a08b4b9d
Revises: 
Create Date: 2026-03-10 21:51:58.260036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd325a08b4b9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('clinician_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinician_alerts')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_clinician_alerts_idempotency_key'))
    )
    op.create_index(op.f('ix_clinician_alerts_tenant_id'), 'clinician_alerts', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    op.create_table('outbox_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_key', sa.String(length=200), nullable=False),
    sa.Column('message_type', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_entries')),
    sa.UniqueConstraint('delivery_key', name=op.f('uq_outbox_entries_delivery_key'))
    )
    op.create_index(op.f('ix_outbox_entries_status'), 'outbox_entries', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_entries_tenant_id'), 'outbox_entries', ['tenant_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('external_patient_id', sa.String(length=100), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('unanswered_count', sa.Integer(), nullable=False),
    sa.Column('last_outreach_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_patient_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients')),
    sa.UniqueConstraint('tenant_id', 'external_patient_id', name='uq_patients_tenant_external')
    )
    op.create_index(op.f('ix_patients_tenant_id'), 'patients', ['tenant_id'], unique=False)
    op.create_table('processed_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('source_event_key', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processed_events')),
    sa.UniqueConstraint('source_event_key', name=op.f('uq_processed_events_source_event_key'))
    )
    op.create_index(op.f('ix_processed_events_tenant_id'), 'processed_events', ['tenant_id'], unique=False)
    op.create_table('safety_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_safety_decisions'))
    )
    op.create_index(op.f('ix_safety_decisions_tenant_id'), 'safety_decisions', ['tenant_id'], unique=False)
    op.create_table('tool_invocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('tool_name', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_invocations')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_tool_invocations_idempotency_key'))
    )
    op.create_index(op.f('ix_tool_invocations_tenant_id'), 'tool_invocations', ['tenant_id'], unique=False)
    op.create_table('conversation_threads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_conversation_threads_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_threads')),
    sa.UniqueConstraint('thread_id', name=op.f('uq_conversation_threads_thread_id'))
    )
    op.create_index(op.f('ix_conversation_threads_tenant_id'), 'conversation_threads', ['tenant_id'], unique=False)
    op.create_table('delivery_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('outbox_entry_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('delivery_receipt', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['outbox_entry_id'], ['outbox_entries.id'], name=op.f('fk_delivery_attempts_outbox_entry_id_outbox_entries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_attempts'))
    )
    op.create_index(op.f('ix_delivery_attempts_tenant_id'), 'delivery_attempts', ['tenant_id'], unique=False)
    op.create_table('patient_consent_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('consented', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_patient_consent_snapshots_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_consent_snapshots'))
    )
    op.create_index(op.f('ix_patient_consent_snapshots_tenant_id'), 'patient_consent_snapshots', ['tenant_id'], unique=False)
    op.create_table('patient_goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('goal_text', sa.Text(), nullable=False),
    sa.Column('raw_patient_text', sa.Text(), nullable=False),
    sa.Column('structured_goal', sa.JSON(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_patient_goals_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_goals')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_patient_goals_idempotency_key'))
    )
    op.create_index(op.f('ix_patient_goals_tenant_id'), 'patient_goals', ['tenant_id'], unique=False)
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_scheduled_jobs_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_jobs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_scheduled_jobs_idempotency_key'))
    )
    op.create_index('ix_scheduled_jobs_pending', 'scheduled_jobs', ['status', 'scheduled_at'], unique=False, postgresql_where="status = 'pending'")
    op.create_index(op.f('ix_scheduled_jobs_status'), 'scheduled_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_scheduled_jobs_tenant_id'), 'scheduled_jobs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_jobs_tenant_id'), table_name='scheduled_jobs')
    op.drop_index(op.f('ix_scheduled_jobs_status'), table_name='scheduled_jobs')
    op.drop_index('ix_scheduled_jobs_pending', table_name='scheduled_jobs', postgresql_where="status = 'pending'")
    op.drop_table('scheduled_jobs')
    op.drop_index(op.f('ix_patient_goals_tenant_id'), table_name='patient_goals')
    op.drop_table('patient_goals')
    op.drop_index(op.f('ix_patient_consent_snapshots_tenant_id'), table_name='patient_consent_snapshots')
    op.drop_table('patient_consent_snapshots')
    op.drop_index(op.f('ix_delivery_attempts_tenant_id'), table_name='delivery_attempts')
    op.drop_table('delivery_attempts')
    op.drop_index(op.f('ix_conversation_threads_tenant_id'), table_name='conversation_threads')
    op.drop_table('conversation_threads')
    op.drop_index(op.f('ix_tool_invocations_tenant_id'), table_name='tool_invocations')
    op.drop_table('tool_invocations')
    op.drop_index(op.f('ix_safety_decisions_tenant_id'), table_name='safety_decisions')
    op.drop_table('safety_decisions')
    op.drop_index(op.f('ix_processed_events_tenant_id'), table_name='processed_events')
    op.drop_table('processed_events')
    op.drop_index(op.f('ix_patients_tenant_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_outbox_entries_tenant_id'), table_name='outbox_entries')
    op.drop_index(op.f('ix_outbox_entries_status'), table_name='outbox_entries')
    op.drop_table('outbox_entries')
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_clinician_alerts_tenant_id'), table_name='clinician_alerts')
    op.drop_table('clinician_alerts')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
